name: CI

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Downloads latest version of the Covid-19 dataset
    - name: Download latest version of the Covid-19 dataset
      run: |
        FILE=./resources/data/covid19.json
        echo "Downloading Covid-19 dataset."
        url="https://opendata.ecdc.europa.eu/covid19/casedistribution/json/"
        response=$(curl -f "$url")
        status=$?
        if [ $status -eq 0 ]; then
          echo $response > $FILE
          echo "$FILE saved."
        else
          echo "curl exit code: ($status) $response"
          exit $status
        fi
    - name: Replace old Covid-19 dataset
      env:
        GIT_OWNER_EMAIL: ${{ secrets.GIT_OWNER_EMAIL }}
        GIT_OWNER_USERNAME: ${{ secrets.GIT_OWNER_USERNAME }}
        PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
      run: |
        git config user.email "$GIT_OWNER_EMAIL"
        git config user.name "$GIT_OWNER_USERNAME"
        if [[ `git status --porcelain` ]]; then
          git add .
          git commit -a -m "Update Covid-19 dataset"
          git remote rm origin
          git remote add origin https://$GIT_OWNER_USERNAME:$PUSH_TOKEN@github.com/$GIT_OWNER_USERNAME/curvacovid19.git
          git push origin HEAD:master
        else
          echo 'Nothing to do'
        fi
